
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 02 18:43:01 CET 2017
//----------------------------------------------------

package com.jgg.sdp.parser.db2.lang;

/** CUP generated interface containing symbol constants. */
public interface DDLSym {
  /* terminals */
  public static final int STOGROUP = 24;
  public static final int SEQUENCE = 23;
  public static final int PROCEDURE = 20;
  public static final int MASK = 18;
  public static final int TRIGGER = 30;
  public static final int ALIAS = 7;
  public static final int ROLE = 22;
  public static final int FUNCTION = 15;
  public static final int PERMISSION = 19;
  public static final int ID = 2;
  public static final int TABLE = 26;
  public static final int TEMPORARY = 28;
  public static final int TYPE = 32;
  public static final int CREATE = 12;
  public static final int COMMA = 3;
  public static final int AUXILIARY = 9;
  public static final int EOF = 0;
  public static final int DATABASE = 13;
  public static final int ALTER = 8;
  public static final int COMMENT = 10;
  public static final int DROP = 14;
  public static final int SYNONIM = 25;
  public static final int error = 1;
  public static final int CONTEXT = 11;
  public static final int PREHOST = 6;
  public static final int GLOBAL = 16;
  public static final int RENAME = 21;
  public static final int VIEW = 33;
  public static final int TRUSTED = 31;
  public static final int HOSTVAR2 = 5;
  public static final int HOSTVAR1 = 4;
  public static final int TABLESPACE = 27;
  public static final int INDEX = 17;
  public static final int TO = 29;
}

