
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 17 19:35:32 CEST 2017
//----------------------------------------------------

package com.jgg.sdp.calculator;

/** CUP generated interface containing symbol constants. */
public interface CalcSym {
  /* terminals */
  public static final int MOD = 16;
  public static final int AND = 7;
  public static final int LT = 24;
  public static final int NE = 21;
  public static final int LOG2 = 4;
  public static final int PLUS = 12;
  public static final int OR = 8;
  public static final int LN = 5;
  public static final int POW = 17;
  public static final int GT = 22;
  public static final int LE = 25;
  public static final int LOG = 3;
  public static final int EXP = 6;
  public static final int EOF = 0;
  public static final int NUMBER = 9;
  public static final int MULT = 14;
  public static final int DIV = 15;
  public static final int ABS = 2;
  public static final int GE = 23;
  public static final int MINUS = 13;
  public static final int error = 1;
  public static final int EQ = 20;
  public static final int ENDS = 26;
  public static final int RPAR = 19;
  public static final int STORE = 11;
  public static final int LPAR = 18;
  public static final int VAR = 10;
}

