
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jan 08 20:16:35 CET 2018
//----------------------------------------------------

package com.jgg.sdp.parser.lang;

/** CUP generated interface containing symbol constants. */
public interface COPYSym {
  /* terminals */
  public static final int ID = 4;
  public static final int IN = 5;
  public static final int error = 1;
  public static final int SUPPRESS = 2;
  public static final int REPLACING = 3;
  public static final int EOF = 0;
  public static final int OF = 6;
}

