
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Apr 11 12:01:34 CEST 2017
//----------------------------------------------------

package com.jgg.sdp.parser.cobol.lang;

/** CUP generated interface containing symbol constants. */
public interface ZCDSym {
  /* terminals */
  public static final int OCCURS = 63;
  public static final int SDPMASTER = 96;
  public static final int POINTER = 66;
  public static final int PACKED = 60;
  public static final int RECORDING = 39;
  public static final int DYNAMIC = 31;
  public static final int RELATIVE = 42;
  public static final int RENAMES = 59;
  public static final int ORGANIZATION = 37;
  public static final int PGMID = 20;
  public static final int LOCAL_SECTION = 12;
  public static final int BLOB = 48;
  public static final int SD = 43;
  public static final int LINAGE = 36;
  public static final int THRU = 87;
  public static final int REMARKS = 25;
  public static final int RANDOM = 38;
  public static final int HEX_VAL = 7;
  public static final int FILLER = 57;
  public static final int USAGE = 77;
  public static final int DIV_ENV = 3;
  public static final int OBJECT_COMPUTER = 19;
  public static final int NUMERO = 6;
  public static final int PIC_DEC = 69;
  public static final int ACCESS = 26;
  public static final int SQLDATA = 93;
  public static final int DISPLAY = 85;
  public static final int LITCONCAT = 9;
  public static final int LITERAL = 8;
  public static final int FD = 32;
  public static final int PIC_NUM = 71;
  public static final int ALTERNATE = 27;
  public static final int PICTURE = 61;
  public static final int DFHCICS = 56;
  public static final int RECORD = 41;
  public static final int DEPENDING = 64;
  public static final int END_SQL = 94;
  public static final int CLASS = 83;
  public static final int SELECT = 45;
  public static final int HIGHVAL = 79;
  public static final int FILE_SECTION = 10;
  public static final int ZERO = 78;
  public static final int QUOTE = 81;
  public static final int INDEX = 34;
  public static final int ORDER = 65;
  public static final int SDPDESC = 95;
  public static final int LPAR = 88;
  public static final int ASSIGN = 28;
  public static final int INSTALLATION = 24;
  public static final int LOWVAL = 80;
  public static final int DEC_POINT = 84;
  public static final int FILE_CONTROL = 14;
  public static final int RECORDS = 40;
  public static final int PIC_DEC_EMPTY = 70;
  public static final int DATEW = 22;
  public static final int CONF_SECTION = 15;
  public static final int NULL = 82;
  public static final int EOF = 0;
  public static final int RPAR = 89;
  public static final int ROWID = 75;
  public static final int PIC_ALPHA = 68;
  public static final int DATEC = 23;
  public static final int LABEL = 35;
  public static final int PIC_ALPHANUM = 67;
  public static final int IN = 91;
  public static final int SOURCE_COMPUTER = 18;
  public static final int error = 1;
  public static final int COMP6 = 55;
  public static final int COMP5 = 54;
  public static final int BLOB_LOCATOR = 49;
  public static final int COMP4 = 53;
  public static final int DATA = 30;
  public static final int COMP3 = 52;
  public static final int COMP2 = 51;
  public static final int COMP1 = 50;
  public static final int INDEXED = 33;
  public static final int ID = 5;
  public static final int PIC_FMT = 72;
  public static final int BLOCK = 29;
  public static final int SPACES = 76;
  public static final int OF = 92;
  public static final int BINARY = 47;
  public static final int PIC_V = 74;
  public static final int REDEFINES = 58;
  public static final int SEQUENTIAL = 44;
  public static final int AUTHOR = 21;
  public static final int SPECIAL_NAMES = 17;
  public static final int STATUS = 46;
  public static final int PIC_LEN = 73;
  public static final int VALUE = 62;
  public static final int TO = 90;
  public static final int IO_SECTION = 16;
  public static final int ENDD = 86;
  public static final int WORKING_SECTION = 11;
  public static final int DIV_ID = 2;
  public static final int LINKAGE_SECTION = 13;
  public static final int DIV_DATA = 4;
}

