
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 02 12:03:56 CET 2017
//----------------------------------------------------

package com.jgg.sdp.parser.cics.lang;

/** CUP generated interface containing symbol constants. */
public interface CICSSym {
  /* terminals */
  public static final int DECIMAL = 2;
  public static final int LENGTH = 6;
  public static final int IN = 5;
  public static final int LITERAL = 7;
  public static final int ENTERO = 3;
  public static final int LPAR = 8;
  public static final int OF = 9;
  public static final int EOF = 0;
  public static final int ID = 4;
  public static final int error = 1;
  public static final int RPAR = 10;
}

