
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jan 08 20:16:46 CET 2018
//----------------------------------------------------

package com.jgg.sdp.ivp.lang;

/** CUP generated interface containing symbol constants. */
public interface CUPSym {
  /* terminals */
  public static final int RBRACK = 23;
  public static final int LT = 26;
  public static final int INIT = 7;
  public static final int NONASSOC = 20;
  public static final int SEMI = 11;
  public static final int LBRACK = 22;
  public static final int PRECEDENCE = 17;
  public static final int PERCENT_PREC = 21;
  public static final int CODE = 2;
  public static final int GT = 25;
  public static final int COLON = 14;
  public static final int NON = 6;
  public static final int ID = 27;
  public static final int WITH = 9;
  public static final int RIGHT = 19;
  public static final int TERMINAL = 5;
  public static final int LEFT = 18;
  public static final int COLON_COLON_EQUALS = 15;
  public static final int COMMA = 12;
  public static final int NONTERMINAL = 24;
  public static final int EOF = 0;
  public static final int PARSER = 4;
  public static final int error = 1;
  public static final int DOT = 13;
  public static final int ACTION = 3;
  public static final int START = 10;
  public static final int SCAN = 8;
  public static final int BAR = 16;
}

