
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Sep 20 13:06:53 CEST 2017
//----------------------------------------------------

package com.jgg.sdp.parser.lang;

/** CUP generated interface containing symbol constants. */
public interface DCLSym {
  /* terminals */
  public static final int PLAN = 27;
  public static final int PRIVILEGES = 28;
  public static final int WITH = 42;
  public static final int OUTPUT = 25;
  public static final int INPUT = 19;
  public static final int TIME = 39;
  public static final int DATE = 9;
  public static final int OPTION = 24;
  public static final int RPAR = 33;
  public static final int STACKED = 35;
  public static final int GRANT = 17;
  public static final int COMMA = 6;
  public static final int GET = 16;
  public static final int VERSION = 41;
  public static final int REVOKE = 31;
  public static final int DEPENDENT = 11;
  public static final int MIN = 23;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int TABLE = 37;
  public static final int BY = 5;
  public static final int error = 1;
  public static final int TIMESTAMP = 38;
  public static final int INCLUDING = 18;
  public static final int DIAGNOSTICS = 13;
  public static final int FROM = 15;
  public static final int LITERAL = 3;
  public static final int CURSOR = 8;
  public static final int EXPLAIN = 14;
  public static final int TO = 40;
  public static final int PACKAGE = 26;
  public static final int PUBLIC = 30;
  public static final int STMTCACHE = 36;
  public static final int SMALLINT = 34;
  public static final int LPAR = 20;
  public static final int ALL = 4;
  public static final int DEC = 10;
  public static final int CURRENT = 7;
  public static final int DESCRIBE = 12;
  public static final int MAX = 21;
  public static final int PROCEDURE = 29;
  public static final int MESSAGE_TEXT = 22;
  public static final int ROLE = 32;
}

