
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 24 22:32:29 CET 2017
//----------------------------------------------------

package com.jgg.sdp.parser.lang;

/** CUP generated interface containing symbol constants. */
public interface DDLSym {
  /* terminals */
  public static final int STOGROUP = 25;
  public static final int SEQUENCE = 24;
  public static final int PROCEDURE = 21;
  public static final int MASK = 19;
  public static final int TRIGGER = 31;
  public static final int ALIAS = 8;
  public static final int ROLE = 23;
  public static final int FUNCTION = 16;
  public static final int LITERAL = 3;
  public static final int PERMISSION = 20;
  public static final int ID = 2;
  public static final int TABLE = 27;
  public static final int TEMPORARY = 29;
  public static final int TYPE = 33;
  public static final int CREATE = 13;
  public static final int COMMA = 4;
  public static final int AUXILIARY = 10;
  public static final int EOF = 0;
  public static final int DATABASE = 14;
  public static final int ALTER = 9;
  public static final int COMMENT = 11;
  public static final int DROP = 15;
  public static final int SYNONIM = 26;
  public static final int error = 1;
  public static final int CONTEXT = 12;
  public static final int PREHOST = 7;
  public static final int GLOBAL = 17;
  public static final int RENAME = 22;
  public static final int VIEW = 34;
  public static final int TRUSTED = 32;
  public static final int HOSTVAR2 = 6;
  public static final int HOSTVAR1 = 5;
  public static final int TABLESPACE = 28;
  public static final int INDEX = 18;
  public static final int TO = 30;
}

