
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Aug 23 15:52:45 CEST 2017
//----------------------------------------------------

package com.jgg.sdp.parser.lang;

/** CUP generated interface containing symbol constants. */
public interface PCLSym {
  /* terminals */
  public static final int SENSITIVE = 55;
  public static final int PREHOST = 6;
  public static final int WITH = 65;
  public static final int INSENSITIVE = 37;
  public static final int ASSOCIATE = 13;
  public static final int USING = 63;
  public static final int HOSTVAR2 = 4;
  public static final int HOSTVAR1 = 3;
  public static final int CONTINUE = 20;
  public static final int EXECUTE = 26;
  public static final int WHENEVER = 64;
  public static final int ROWS = 53;
  public static final int FOR = 29;
  public static final int BEFORE = 15;
  public static final int FOUND = 30;
  public static final int RELATIVE = 48;
  public static final int NOT = 43;
  public static final int RPAR = 51;
  public static final int FIRST = 28;
  public static final int SQLWARNING = 59;
  public static final int COMMA = 9;
  public static final int CALL = 17;
  public static final int BEGIN = 16;
  public static final int ROWSET = 52;
  public static final int NEXT = 42;
  public static final int ID = 2;
  public static final int PREPARE = 45;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int SQLERROR = 58;
  public static final int INCLUDE = 36;
  public static final int IMMEDIATE = 35;
  public static final int STARTING = 60;
  public static final int IDQUALIFIED = 5;
  public static final int DECLARE = 23;
  public static final int FROM = 32;
  public static final int PRIOR = 46;
  public static final int INTO = 38;
  public static final int ABSOLUTE = 10;
  public static final int LITERAL = 7;
  public static final int LAST = 39;
  public static final int CURSOR = 22;
  public static final int ALLOCATE = 12;
  public static final int TO = 61;
  public static final int GOTO = 33;
  public static final int FETCH = 27;
  public static final int OPEN = 44;
  public static final int AFTER = 11;
  public static final int END = 25;
  public static final int NUM_ENTERO = 8;
  public static final int LPAR = 41;
  public static final int CONNECT = 19;
  public static final int RESET = 49;
  public static final int HOLD = 34;
  public static final int USER = 62;
  public static final int AT = 14;
  public static final int CLOSE = 18;
  public static final int SECTION = 54;
  public static final int CURRENT = 21;
  public static final int LOCATOR = 40;
  public static final int SIGNAL = 57;
  public static final int PROCEDURE = 47;
  public static final int DESCRIPTOR = 24;
  public static final int SET = 56;
  public static final int RESULT = 50;
  public static final int FREE = 31;
}

