
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Sep 09 02:43:26 CEST 2017
//----------------------------------------------------

import java.util.*;
import java.io.*;
import java_cup.runtime.Symbol;
import java_cup.runtime.ComplexSymbolFactory.ComplexSymbol;
import java_cup.runtime.ComplexSymbolFactory;
import minijava.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sat Sep 09 02:43:26 CEST 2017
  */
public class MinijavaCup extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public MinijavaCup() {super();}

  /** Constructor which sets the default scanner. */
  public MinijavaCup(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public MinijavaCup(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\035\000\002\002\004\000\002\002\004\000\002\003" +
    "\004\000\002\003\002\000\002\005\004\000\002\005\002" +
    "\000\002\004\006\000\002\006\005\000\002\006\002\000" +
    "\002\007\003\000\002\007\005\000\002\007\006\000\002" +
    "\007\010\000\002\007\011\000\002\007\007\000\002\007" +
    "\007\000\002\007\007\000\002\007\011\000\002\007\007" +
    "\000\002\011\003\000\002\011\005\000\002\011\005\000" +
    "\002\011\004\000\002\011\005\000\002\010\003\000\002" +
    "\010\003\000\002\010\005\000\002\010\004\000\002\010" +
    "\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\106\000\022\002\ufffe\004\ufffe\010\ufffe\012\ufffe\014" +
    "\ufffe\016\ufffe\021\007\027\ufffe\001\002\000\022\002\ufffe" +
    "\004\ufffe\010\ufffe\012\ufffe\014\ufffe\016\ufffe\021\007\027" +
    "\ufffe\001\002\000\004\002\107\001\002\000\020\002\ufffc" +
    "\004\ufffc\010\ufffc\012\ufffc\014\ufffc\016\ufffc\027\ufffc\001" +
    "\002\000\004\027\010\001\002\000\006\004\ufff9\005\ufff9" +
    "\001\002\000\006\004\013\005\012\001\002\000\004\027" +
    "\014\001\002\000\022\002\ufffb\004\ufffb\010\ufffb\012\ufffb" +
    "\014\ufffb\016\ufffb\021\ufffb\027\ufffb\001\002\000\006\004" +
    "\ufffa\005\ufffa\001\002\000\020\002\001\004\016\010\017" +
    "\012\024\014\023\016\020\027\022\001\002\000\024\002" +
    "\ufff8\004\ufff8\010\ufff8\011\ufff8\012\ufff8\013\ufff8\014\ufff8" +
    "\016\ufff8\027\ufff8\001\002\000\020\004\ufffc\010\ufffc\011" +
    "\ufffc\012\ufffc\014\ufffc\016\ufffc\027\ufffc\001\002\000\004" +
    "\006\076\001\002\000\022\002\ufffd\004\ufffd\010\ufffd\011" +
    "\ufffd\012\ufffd\014\ufffd\016\ufffd\027\ufffd\001\002\000\004" +
    "\020\064\001\002\000\004\006\060\001\002\000\004\006" +
    "\025\001\002\000\016\006\031\017\027\022\033\026\026" +
    "\027\032\031\034\001\002\000\014\004\uffe8\007\uffe8\022" +
    "\uffe8\024\uffe8\025\uffe8\001\002\000\016\006\031\017\027" +
    "\022\033\026\026\027\032\031\034\001\002\000\006\007" +
    "\053\025\050\001\002\000\016\006\031\017\027\022\033" +
    "\026\026\027\032\031\034\001\002\000\014\004\uffe9\007" +
    "\uffe9\022\uffe9\024\uffe9\025\uffe9\001\002\000\012\006\040" +
    "\022\033\026\026\027\032\001\002\000\006\007\uffee\025" +
    "\uffee\001\002\000\006\022\037\024\036\001\002\000\012" +
    "\006\040\022\033\026\026\027\032\001\002\000\012\006" +
    "\040\022\033\026\026\027\032\001\002\000\012\006\040" +
    "\022\033\026\026\027\032\001\002\000\014\004\uffe5\007" +
    "\uffe5\022\uffe5\024\uffe5\025\uffe5\001\002\000\006\007\043" +
    "\022\037\001\002\000\014\004\uffe7\007\uffe7\022\uffe7\024" +
    "\uffe7\025\uffe7\001\002\000\010\007\uffec\022\037\025\uffec" +
    "\001\002\000\014\004\uffe6\007\uffe6\022\uffe6\024\uffe6\025" +
    "\uffe6\001\002\000\006\007\051\025\050\001\002\000\010" +
    "\007\043\022\037\024\036\001\002\000\016\006\031\017" +
    "\027\022\033\026\026\027\032\031\034\001\002\000\006" +
    "\007\uffed\025\uffed\001\002\000\006\007\uffea\025\uffea\001" +
    "\002\000\016\004\016\010\017\012\024\014\023\016\020" +
    "\027\022\001\002\000\024\002\ufff1\004\ufff1\010\ufff1\011" +
    "\ufff1\012\ufff1\013\055\014\ufff1\016\ufff1\027\ufff1\001\002" +
    "\000\016\004\016\010\017\012\024\014\023\016\020\027" +
    "\022\001\002\000\024\002\ufff0\004\ufff0\010\ufff0\011\ufff0" +
    "\012\ufff0\013\ufff0\014\ufff0\016\ufff0\027\ufff0\001\002\000" +
    "\006\007\uffeb\025\uffeb\001\002\000\016\006\031\017\027" +
    "\022\033\026\026\027\032\031\034\001\002\000\006\007" +
    "\062\025\050\001\002\000\016\004\016\010\017\012\024" +
    "\014\023\016\020\027\022\001\002\000\024\002\uffef\004" +
    "\uffef\010\uffef\011\uffef\012\uffef\013\uffef\014\uffef\016\uffef" +
    "\027\uffef\001\002\000\014\006\040\015\065\022\033\026" +
    "\026\027\032\001\002\000\004\006\070\001\002\000\006" +
    "\004\067\022\037\001\002\000\024\002\ufff6\004\ufff6\010" +
    "\ufff6\011\ufff6\012\ufff6\013\ufff6\014\ufff6\016\ufff6\027\ufff6" +
    "\001\002\000\006\007\072\030\071\001\002\000\004\007" +
    "\074\001\002\000\004\004\073\001\002\000\024\002\ufff5" +
    "\004\ufff5\010\ufff5\011\ufff5\012\ufff5\013\ufff5\014\ufff5\016" +
    "\ufff5\027\ufff5\001\002\000\004\004\075\001\002\000\024" +
    "\002\ufff4\004\ufff4\010\ufff4\011\ufff4\012\ufff4\013\ufff4\014" +
    "\ufff4\016\ufff4\027\ufff4\001\002\000\014\006\040\022\033" +
    "\026\026\027\032\030\077\001\002\000\004\007\103\001" +
    "\002\000\006\007\101\022\037\001\002\000\004\004\102" +
    "\001\002\000\024\002\ufff3\004\ufff3\010\ufff3\011\ufff3\012" +
    "\ufff3\013\ufff3\014\ufff3\016\ufff3\027\ufff3\001\002\000\004" +
    "\004\104\001\002\000\024\002\ufff2\004\ufff2\010\ufff2\011" +
    "\ufff2\012\ufff2\013\ufff2\014\ufff2\016\ufff2\027\ufff2\001\002" +
    "\000\020\004\016\010\017\011\106\012\024\014\023\016" +
    "\020\027\022\001\002\000\024\002\ufff7\004\ufff7\010\ufff7" +
    "\011\ufff7\012\ufff7\013\ufff7\014\ufff7\016\ufff7\027\ufff7\001" +
    "\002\000\004\002\000\001\002\000\020\002\uffff\004\uffff" +
    "\010\uffff\012\uffff\014\uffff\016\uffff\027\uffff\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\106\000\010\002\004\003\005\004\003\001\001\000" +
    "\006\003\107\004\003\001\001\000\002\001\001\000\004" +
    "\005\014\001\001\000\002\001\001\000\004\006\010\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\007\020\001\001\000\002\001" +
    "\001\000\004\005\104\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\010\034\011\027\001\001\000\002\001\001" +
    "\000\006\010\034\011\056\001\001\000\002\001\001\000" +
    "\006\010\046\011\045\001\001\000\002\001\001\000\004" +
    "\010\044\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\010\043\001\001\000\004\010\040\001\001\000\004" +
    "\010\041\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\010\034\011\051\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\007\053" +
    "\001\001\000\002\001\001\000\004\007\055\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\010\034\011\060" +
    "\001\001\000\002\001\001\000\004\007\062\001\001\000" +
    "\002\001\001\000\004\010\065\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\010\077\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\007" +
    "\020\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$MinijavaCup$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$MinijavaCup$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$MinijavaCup$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


 
  public boolean syntaxErrors;


  Lexer lexer;

  public Parser(Lexer lex, ComplexSymbolFactory sf) {
    super(lex,sf);
    lexer = lex;
  }
//  public void report_fatal_error(String message, Object info){
//      System.out.println("Fatal: ");
//  }
  
  public void report_error(String message, Object info) {
    syntaxErrors = true;
    
    System.out.println(message+" at");
    
    if ( !(info instanceof ComplexSymbol) ) return;
    System.out.println(info);
    return;
  }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$MinijavaCup$actions {
  private final MinijavaCup parser;

  /** Constructor */
  CUP$MinijavaCup$actions(MinijavaCup parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$MinijavaCup$do_action(
    int                        CUP$MinijavaCup$act_num,
    java_cup.runtime.lr_parser CUP$MinijavaCup$parser,
    java.util.Stack            CUP$MinijavaCup$stack,
    int                        CUP$MinijavaCup$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$MinijavaCup$result;

      /* select the action based on the action number */
      switch (CUP$MinijavaCup$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expr ::= expr BINOP expr 
            {
              Expr RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).right;
		Expr e1 = (Expr)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).right;
		Integer op = (Integer)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()).right;
		Expr e2 = (Expr)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.peek()).value;
		 RESULT = Expr.binop(e1,op,e2); 
              CUP$MinijavaCup$result = parser.getSymbolFactory().newSymbol("expr",6, ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)), ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), RESULT);
            }
          return CUP$MinijavaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expr ::= BINOP expr 
            {
              Expr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.peek()).value;
		 RESULT = Expr.unop(e); 
              CUP$MinijavaCup$result = parser.getSymbolFactory().newSymbol("expr",6, ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)), ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), RESULT);
            }
          return CUP$MinijavaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // expr ::= LPAR expr RPAR 
            {
              Expr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).value;
		 RESULT = Expr.priority(e); 
              CUP$MinijavaCup$result = parser.getSymbolFactory().newSymbol("expr",6, ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)), ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), RESULT);
            }
          return CUP$MinijavaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // expr ::= INTCONST 
            {
              Expr RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()).right;
		Integer c = (Integer)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.peek()).value;
		 RESULT = Expr.intconst(c); 
              CUP$MinijavaCup$result = parser.getSymbolFactory().newSymbol("expr",6, ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), RESULT);
            }
          return CUP$MinijavaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // expr ::= IDENT 
            {
              Expr RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.peek()).value;
		 RESULT = Expr.ident(i); 
              CUP$MinijavaCup$result = parser.getSymbolFactory().newSymbol("expr",6, ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), RESULT);
            }
          return CUP$MinijavaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // cond ::= cond BBINOP cond 
            {
              Cond RESULT =null;
		int c1left = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).left;
		int c1right = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).right;
		Cond c1 = (Cond)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).right;
		Integer op = (Integer)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).value;
		int c2left = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()).left;
		int c2right = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()).right;
		Cond c2 = (Cond)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.peek()).value;
		 RESULT = Cond.binop(c1,op,c2); 
              CUP$MinijavaCup$result = parser.getSymbolFactory().newSymbol("cond",7, ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)), ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), RESULT);
            }
          return CUP$MinijavaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // cond ::= BUNOP cond 
            {
              Cond RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()).right;
		Cond c = (Cond)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.peek()).value;
		 RESULT = Cond.unop(c); 
              CUP$MinijavaCup$result = parser.getSymbolFactory().newSymbol("cond",7, ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)), ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), RESULT);
            }
          return CUP$MinijavaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // cond ::= expr COMP expr 
            {
              Cond RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).right;
		Expr e1 = (Expr)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).right;
		Integer op = (Integer)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()).right;
		Expr e2 = (Expr)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.peek()).value;
		 RESULT = Cond.binop(e1,op,e2); 
              CUP$MinijavaCup$result = parser.getSymbolFactory().newSymbol("cond",7, ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)), ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), RESULT);
            }
          return CUP$MinijavaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // cond ::= LPAR cond RPAR 
            {
              Cond RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).right;
		Cond c = (Cond)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).value;
		 RESULT = Cond.priority(c); 
              CUP$MinijavaCup$result = parser.getSymbolFactory().newSymbol("cond",7, ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)), ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), RESULT);
            }
          return CUP$MinijavaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // cond ::= BOOLCONST 
            {
              Cond RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()).right;
		Boolean c = (Boolean)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.peek()).value;
		 RESULT = Cond.boolconst(c); 
              CUP$MinijavaCup$result = parser.getSymbolFactory().newSymbol("cond",7, ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), RESULT);
            }
          return CUP$MinijavaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // stmt ::= WHILE LPAR cond RPAR stmt 
            {
              Stmt RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).right;
		Cond c = (Cond)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()).right;
		Stmt s = (Stmt)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.peek()).value;
		 RESULT = Stmt.whileloop(c,s); 
              CUP$MinijavaCup$result = parser.getSymbolFactory().newSymbol("stmt",5, ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-4)), ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), RESULT);
            }
          return CUP$MinijavaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // stmt ::= IF LPAR cond RPAR stmt ELSE stmt 
            {
              Stmt RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-4)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-4)).right;
		Cond c = (Cond)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-4)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).right;
		Stmt t = (Stmt)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()).right;
		Stmt e = (Stmt)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.peek()).value;
		 RESULT = Stmt.ifthenelse(c,t,e); 
              CUP$MinijavaCup$result = parser.getSymbolFactory().newSymbol("stmt",5, ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-6)), ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), RESULT);
            }
          return CUP$MinijavaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // stmt ::= IF LPAR cond RPAR stmt 
            {
              Stmt RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).right;
		Cond c = (Cond)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()).right;
		Stmt s = (Stmt)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.peek()).value;
		 RESULT = Stmt.ifthen(c,s); 
              CUP$MinijavaCup$result = parser.getSymbolFactory().newSymbol("stmt",5, ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-4)), ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), RESULT);
            }
          return CUP$MinijavaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // stmt ::= WRITE LPAR STRINGCONST RPAR SEMICOLON 
            {
              Stmt RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).value;
		 RESULT = Stmt.write(s); 
              CUP$MinijavaCup$result = parser.getSymbolFactory().newSymbol("stmt",5, ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-4)), ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), RESULT);
            }
          return CUP$MinijavaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // stmt ::= WRITE LPAR expr RPAR SEMICOLON 
            {
              Stmt RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).value;
		 RESULT = Stmt.write(e); 
              CUP$MinijavaCup$result = parser.getSymbolFactory().newSymbol("stmt",5, ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-4)), ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), RESULT);
            }
          return CUP$MinijavaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // stmt ::= IDENT ASSIGN READ LPAR STRINGCONST RPAR SEMICOLON 
            {
              Stmt RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-6)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-6)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-6)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).value;
		 RESULT = Stmt.read(i,s); 
              CUP$MinijavaCup$result = parser.getSymbolFactory().newSymbol("stmt",5, ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-6)), ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), RESULT);
            }
          return CUP$MinijavaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // stmt ::= IDENT ASSIGN READ LPAR RPAR SEMICOLON 
            {
              Stmt RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-5)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-5)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-5)).value;
		 RESULT = Stmt.read(i); 
              CUP$MinijavaCup$result = parser.getSymbolFactory().newSymbol("stmt",5, ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-5)), ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), RESULT);
            }
          return CUP$MinijavaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // stmt ::= IDENT ASSIGN expr SEMICOLON 
            {
              Stmt RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-3)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-3)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).value;
		 RESULT = Stmt.assign(i,e); 
              CUP$MinijavaCup$result = parser.getSymbolFactory().newSymbol("stmt",5, ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-3)), ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), RESULT);
            }
          return CUP$MinijavaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // stmt ::= BEGIN stmtlist END 
            {
              Stmt RESULT =null;
		int slleft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).left;
		int slright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).right;
		List<Stmt> sl = (List<Stmt>)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).value;
		 RESULT = Stmt.compound(sl); 
              CUP$MinijavaCup$result = parser.getSymbolFactory().newSymbol("stmt",5, ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)), ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), RESULT);
            }
          return CUP$MinijavaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // stmt ::= SEMICOLON 
            {
              Stmt RESULT =null;
		 RESULT = Stmt.empty(); 
              CUP$MinijavaCup$result = parser.getSymbolFactory().newSymbol("stmt",5, ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), RESULT);
            }
          return CUP$MinijavaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // identlist ::= 
            {
              List<String> RESULT =null;
		 RESULT = new LinkedList<String>(); 
              CUP$MinijavaCup$result = parser.getSymbolFactory().newSymbol("identlist",4, ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), RESULT);
            }
          return CUP$MinijavaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // identlist ::= identlist COMMA IDENT 
            {
              List<String> RESULT =null;
		int illeft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).left;
		int ilright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).right;
		List<String> il = (List<String>)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.peek()).value;
		 il.add(i); RESULT = il; 
              CUP$MinijavaCup$result = parser.getSymbolFactory().newSymbol("identlist",4, ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)), ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), RESULT);
            }
          return CUP$MinijavaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // decl ::= TYPE IDENT identlist SEMICOLON 
            {
              Decl RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-2)).value;
		int illeft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).left;
		int ilright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).right;
		List<String> il = (List<String>)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).value;
		 il.add(0,i); RESULT = new Decl(il); 
              CUP$MinijavaCup$result = parser.getSymbolFactory().newSymbol("decl",2, ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-3)), ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), RESULT);
            }
          return CUP$MinijavaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // stmtlist ::= 
            {
              List<Stmt> RESULT =null;
		 RESULT = new LinkedList<Stmt>(); 
              CUP$MinijavaCup$result = parser.getSymbolFactory().newSymbol("stmtlist",3, ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), RESULT);
            }
          return CUP$MinijavaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // stmtlist ::= stmtlist stmt 
            {
              List<Stmt> RESULT =null;
		int slleft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).left;
		int slright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).right;
		List<Stmt> sl = (List<Stmt>)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()).right;
		Stmt s = (Stmt)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.peek()).value;
		 sl.add(s); RESULT = sl; 
              CUP$MinijavaCup$result = parser.getSymbolFactory().newSymbol("stmtlist",3, ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)), ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), RESULT);
            }
          return CUP$MinijavaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // decllist ::= 
            {
              List<Decl> RESULT =null;
		 RESULT = new LinkedList<Decl>(); 
              CUP$MinijavaCup$result = parser.getSymbolFactory().newSymbol("decllist",1, ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), RESULT);
            }
          return CUP$MinijavaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // decllist ::= decl decllist 
            {
              List<Decl> RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).right;
		Decl d = (Decl)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).value;
		int dlleft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()).left;
		int dlright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()).right;
		List<Decl> dl = (List<Decl>)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.peek()).value;
		 dl.add(d); RESULT = dl; 
              CUP$MinijavaCup$result = parser.getSymbolFactory().newSymbol("decllist",1, ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)), ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), RESULT);
            }
          return CUP$MinijavaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).right;
		Program start_val = (Program)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).value;
		RESULT = start_val;
              CUP$MinijavaCup$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)), ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$MinijavaCup$parser.done_parsing();
          return CUP$MinijavaCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // program ::= decllist stmtlist 
            {
              Program RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).right;
		List<Decl> d = (List<Decl>)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()).right;
		List<Stmt> s = (List<Stmt>)((java_cup.runtime.Symbol) CUP$MinijavaCup$stack.peek()).value;
		 RESULT = new Program(d,s); 
              CUP$MinijavaCup$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.elementAt(CUP$MinijavaCup$top-1)), ((java_cup.runtime.Symbol)CUP$MinijavaCup$stack.peek()), RESULT);
            }
          return CUP$MinijavaCup$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

