/* The following code was generated by JFlex 1.6.1 */

package com.jgg.sdp.parser.lang;

import java_cup.runtime.Symbol;

import com.jgg.sdp.core.ctes.*;
import com.jgg.sdp.core.exceptions.*;
import com.jgg.sdp.parser.base.*;

import static com.jgg.sdp.parser.lang.DB2Sym.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>P:/SDP/Java/SDPParser/src/main/config/DB2Lexer.lex</tt>
 */
public class DB2Lexer extends GenericLexer implements GenericScanner , ILexer, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;
  public static final int QUOTE_STRING = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\4\1\37\1\37\1\5\22\0\1\1\1\0\1\36"+
    "\4\0\1\35\3\0\1\3\1\0\1\2\1\3\1\0\12\2\7\0"+
    "\1\23\1\31\1\6\1\20\1\21\2\2\1\33\1\12\1\2\1\30"+
    "\1\22\1\10\1\26\1\7\1\32\1\2\1\15\1\17\1\13\1\14"+
    "\1\25\1\34\1\24\2\2\4\0\1\2\1\0\1\23\1\31\1\6"+
    "\1\20\1\21\2\2\1\33\1\12\1\2\1\30\1\22\1\10\1\26"+
    "\1\7\1\32\1\2\1\15\1\17\1\13\1\14\1\25\1\34\1\24"+
    "\2\2\1\0\1\0\10\0\1\37\252\0\2\11\115\0\1\16\u1ea8\0"+
    "\1\37\1\37\u0100\0\1\27\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udee5\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\3\1\1\2\14\1\1\3\1\4\1\5\1\6"+
    "\1\7\4\10\2\11\1\12\2\10\3\0\12\10\1\0"+
    "\3\10\3\0\10\10\1\0\1\10\1\13\1\0\3\10"+
    "\3\0\5\10\2\14\2\15\1\0\1\10\1\0\1\10"+
    "\1\0\1\10\1\16\1\10\2\0\1\17\2\10\1\17"+
    "\2\10\2\20\2\21\1\0\2\10\2\0\3\10\1\0"+
    "\1\10\2\22\1\10\2\0\2\10\1\23\1\0\1\10"+
    "\2\24\2\0\2\10\1\0\1\10\1\25\1\26\1\25"+
    "\1\26\2\27";

  private static int [] zzUnpackAction() {
    int [] result = new int[134];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\40\0\100\0\40\0\140\0\200\0\40\0\240"+
    "\0\300\0\340\0\u0100\0\u0120\0\u0140\0\u0160\0\u0180\0\u01a0"+
    "\0\u01c0\0\u01e0\0\u0200\0\40\0\40\0\40\0\40\0\40"+
    "\0\200\0\u0220\0\u0240\0\u0260\0\u0280\0\u02a0\0\200\0\u02c0"+
    "\0\u02e0\0\u0300\0\u0320\0\u0340\0\u0360\0\u0380\0\u03a0\0\u03c0"+
    "\0\u03e0\0\u0400\0\u0420\0\u0440\0\u0460\0\u0480\0\u04a0\0\u04c0"+
    "\0\u04e0\0\u0500\0\u0520\0\u0540\0\u0560\0\u0580\0\u05a0\0\u05c0"+
    "\0\u05e0\0\u0600\0\u0620\0\u0640\0\u0660\0\u0680\0\u06a0\0\200"+
    "\0\u06c0\0\u06e0\0\u0700\0\u0720\0\u0740\0\u0760\0\u0780\0\u07a0"+
    "\0\u07c0\0\u07e0\0\u0800\0\u0820\0\40\0\200\0\40\0\200"+
    "\0\u0840\0\u0860\0\u0880\0\u08a0\0\u08c0\0\u08e0\0\200\0\u0900"+
    "\0\u0920\0\u0940\0\40\0\u0960\0\u0980\0\200\0\u09a0\0\u09c0"+
    "\0\40\0\200\0\40\0\200\0\u09e0\0\u0a00\0\u0a20\0\u0a40"+
    "\0\u0a60\0\u0a80\0\u0aa0\0\u0ac0\0\u0ae0\0\u0b00\0\40\0\200"+
    "\0\u0b20\0\u0b40\0\u0b60\0\u0b80\0\u0ba0\0\200\0\u0bc0\0\u0be0"+
    "\0\40\0\200\0\u0c00\0\u0c20\0\u0c40\0\u0c60\0\u0c80\0\u0ca0"+
    "\0\40\0\40\0\200\0\200\0\40\0\200";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[134];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\4\2\7\1\10\1\6\1\11"+
    "\1\12\1\13\1\14\1\6\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\4\6\1\4\4\6\1\23\3\4\40\0"+
    "\4\24\1\25\1\26\27\24\1\27\1\30\2\0\1\5"+
    "\40\0\2\31\2\0\3\31\1\0\4\31\1\0\10\31"+
    "\1\0\5\31\5\0\2\31\2\0\1\31\1\32\1\31"+
    "\1\0\2\31\1\33\1\31\1\0\10\31\1\0\5\31"+
    "\5\0\2\31\2\0\1\31\1\34\1\31\1\0\4\31"+
    "\1\0\10\31\1\0\5\31\31\0\1\35\13\0\2\31"+
    "\2\0\3\31\1\0\4\31\1\0\7\31\1\36\1\0"+
    "\5\31\5\0\2\31\2\0\1\31\1\37\1\31\1\0"+
    "\4\31\1\0\4\31\1\40\3\31\1\0\5\31\5\0"+
    "\2\31\2\0\1\31\1\41\1\31\1\0\4\31\1\0"+
    "\10\31\1\0\5\31\16\0\1\42\7\0\1\43\7\0"+
    "\1\44\6\0\2\31\2\0\3\31\1\0\1\31\1\45"+
    "\2\31\1\0\4\31\1\46\3\31\1\0\3\31\1\47"+
    "\1\31\5\0\2\31\2\0\3\31\1\0\4\31\1\0"+
    "\2\31\1\50\5\31\1\0\5\31\5\0\2\31\2\0"+
    "\3\31\1\0\4\31\1\0\5\31\1\51\2\31\1\0"+
    "\5\31\5\0\2\31\2\0\1\31\1\52\1\31\1\0"+
    "\4\31\1\0\10\31\1\0\5\31\5\0\2\31\2\0"+
    "\1\31\1\53\1\31\1\0\4\31\1\0\10\31\1\0"+
    "\5\31\5\0\2\31\2\0\2\31\1\54\1\0\4\31"+
    "\1\0\10\31\1\0\5\31\5\0\2\31\2\0\3\31"+
    "\1\0\3\31\1\55\1\0\10\31\1\0\5\31\5\0"+
    "\2\31\2\0\3\31\1\0\4\31\1\0\1\31\1\56"+
    "\6\31\1\0\5\31\11\0\1\57\33\0\2\31\2\0"+
    "\1\60\2\31\1\0\4\31\1\0\10\31\1\0\5\31"+
    "\5\0\2\31\2\0\3\31\1\0\4\31\1\0\10\31"+
    "\1\0\1\31\1\61\3\31\5\0\2\31\2\0\3\31"+
    "\1\0\4\31\1\0\3\31\1\62\4\31\1\0\5\31"+
    "\26\0\1\63\41\0\1\64\35\0\1\65\16\0\2\31"+
    "\2\0\3\31\1\0\4\31\1\0\4\31\1\66\3\31"+
    "\1\0\5\31\5\0\2\31\2\0\3\31\1\0\4\31"+
    "\1\0\6\31\1\67\1\31\1\0\5\31\5\0\2\31"+
    "\2\0\3\31\1\0\4\31\1\0\4\31\1\70\3\31"+
    "\1\0\5\31\5\0\2\31\2\0\1\71\2\31\1\0"+
    "\4\31\1\0\10\31\1\0\5\31\5\0\2\31\2\0"+
    "\1\72\2\31\1\0\4\31\1\0\10\31\1\0\5\31"+
    "\5\0\2\31\2\0\1\73\2\31\1\0\4\31\1\0"+
    "\10\31\1\0\5\31\5\0\2\31\2\0\3\31\1\0"+
    "\3\31\1\74\1\0\10\31\1\0\5\31\5\0\2\31"+
    "\2\0\2\31\1\75\1\0\4\31\1\0\10\31\1\0"+
    "\5\31\5\0\2\31\2\0\3\31\1\0\4\31\1\76"+
    "\1\77\7\31\1\0\5\31\5\0\2\31\2\0\3\31"+
    "\1\0\4\31\1\0\2\31\1\100\5\31\1\0\5\31"+
    "\25\0\1\101\17\0\2\31\2\0\3\31\1\0\4\31"+
    "\1\0\3\31\1\102\4\31\1\0\5\31\5\0\2\31"+
    "\2\0\3\31\1\0\4\31\1\0\3\31\1\103\4\31"+
    "\1\0\5\31\5\0\2\31\2\0\3\31\1\0\4\31"+
    "\1\0\3\31\1\104\4\31\1\0\5\31\16\0\1\105"+
    "\45\0\1\106\33\0\1\107\24\0\2\31\2\0\3\31"+
    "\1\0\1\31\1\110\2\31\1\0\10\31\1\0\5\31"+
    "\5\0\2\31\2\0\3\31\1\0\4\31\1\0\2\31"+
    "\1\111\5\31\1\0\5\31\5\0\2\31\2\0\3\31"+
    "\1\0\3\31\1\112\1\0\10\31\1\0\5\31\5\0"+
    "\2\31\2\0\3\31\1\0\4\31\1\0\3\31\1\113"+
    "\4\31\1\0\5\31\5\0\2\31\2\0\3\31\1\0"+
    "\4\31\1\0\3\31\1\114\4\31\1\0\5\31\5\0"+
    "\2\31\2\0\3\31\1\0\4\31\1\0\10\31\1\115"+
    "\1\116\4\31\5\0\2\31\2\0\3\31\1\0\4\31"+
    "\1\0\10\31\1\117\1\120\4\31\5\0\2\31\2\0"+
    "\3\31\1\121\1\122\3\31\1\0\10\31\1\0\5\31"+
    "\12\0\1\123\32\0\2\31\2\0\1\31\1\124\1\31"+
    "\1\0\4\31\1\0\10\31\1\0\5\31\17\0\1\125"+
    "\25\0\2\31\2\0\3\31\1\0\2\31\1\126\1\31"+
    "\1\0\10\31\1\0\5\31\5\0\2\31\2\0\3\31"+
    "\1\0\4\31\1\0\2\31\1\127\5\31\1\0\5\31"+
    "\5\0\2\31\2\0\3\31\1\0\4\31\1\0\10\31"+
    "\1\0\1\31\1\130\3\31\24\0\1\131\50\0\1\132"+
    "\26\0\1\133\20\0\2\31\2\0\3\31\1\0\4\31"+
    "\1\0\2\31\1\134\5\31\1\0\5\31\5\0\2\31"+
    "\2\0\3\31\1\0\4\31\1\0\10\31\1\0\2\31"+
    "\1\135\2\31\5\0\2\31\2\0\3\31\1\0\4\31"+
    "\1\0\2\31\1\136\5\31\1\0\5\31\5\0\2\31"+
    "\2\0\3\31\1\0\4\31\1\0\4\31\1\137\3\31"+
    "\1\0\5\31\5\0\2\31\2\0\3\31\1\0\2\31"+
    "\1\140\1\31\1\0\10\31\1\0\5\31\16\0\1\141"+
    "\26\0\2\31\2\0\3\31\1\0\1\31\1\142\2\31"+
    "\1\0\10\31\1\0\5\31\20\0\1\143\24\0\2\31"+
    "\2\0\3\31\1\0\3\31\1\144\1\0\10\31\1\0"+
    "\5\31\23\0\1\145\21\0\2\31\2\0\3\31\1\0"+
    "\4\31\1\0\1\31\1\146\6\31\1\0\5\31\5\0"+
    "\2\31\2\0\3\31\1\0\4\31\1\0\4\31\1\147"+
    "\3\31\1\0\5\31\13\0\1\150\36\0\1\151\32\0"+
    "\2\31\2\0\2\31\1\152\1\0\4\31\1\0\10\31"+
    "\1\0\5\31\5\0\2\31\2\0\1\31\1\153\1\31"+
    "\1\0\4\31\1\0\10\31\1\0\5\31\5\0\2\31"+
    "\2\0\3\31\1\0\3\31\1\154\1\0\10\31\1\0"+
    "\5\31\5\0\2\31\2\0\3\31\1\0\4\31\1\155"+
    "\1\156\7\31\1\0\5\31\24\0\1\157\20\0\2\31"+
    "\2\0\3\31\1\0\4\31\1\0\2\31\1\160\5\31"+
    "\1\0\5\31\5\0\2\31\2\0\1\161\2\31\1\0"+
    "\4\31\1\0\10\31\1\0\5\31\24\0\1\162\27\0"+
    "\2\163\27\0\2\31\2\0\3\31\1\0\4\31\1\0"+
    "\2\31\1\164\5\31\1\0\5\31\5\0\2\31\2\0"+
    "\3\31\1\163\1\165\3\31\1\0\10\31\1\0\5\31"+
    "\5\0\2\31\2\0\3\31\1\0\4\31\1\0\2\31"+
    "\1\166\5\31\1\0\5\31\14\0\2\167\27\0\2\31"+
    "\2\0\3\31\1\167\1\170\3\31\1\0\10\31\1\0"+
    "\5\31\5\0\2\31\2\0\3\31\1\0\4\31\1\0"+
    "\10\31\1\171\1\172\4\31\31\0\1\173\37\0\1\174"+
    "\13\0\2\31\2\0\3\31\1\0\4\31\1\0\7\31"+
    "\1\175\1\0\5\31\5\0\2\31\2\0\3\31\1\0"+
    "\4\31\1\0\7\31\1\176\1\0\5\31\30\0\1\177"+
    "\14\0\2\31\2\0\3\31\1\0\4\31\1\0\6\31"+
    "\1\200\1\31\1\0\5\31\16\0\1\201\37\0\1\202"+
    "\26\0\2\31\2\0\3\31\1\0\1\31\1\203\2\31"+
    "\1\0\10\31\1\0\5\31\5\0\2\31\2\0\3\31"+
    "\1\0\1\31\1\204\2\31\1\0\10\31\1\0\5\31"+
    "\24\0\1\205\20\0\2\31\2\0\3\31\1\0\4\31"+
    "\1\0\2\31\1\206\5\31\1\0\5\31\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3264];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\10\1\0\1\11\2\1\1\11\14\1\5\11"+
    "\11\1\3\0\12\1\1\0\3\1\3\0\10\1\1\0"+
    "\2\1\1\0\3\1\3\0\5\1\1\11\1\1\1\11"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\3\1\2\0"+
    "\1\11\5\1\1\11\1\1\1\11\1\1\1\0\2\1"+
    "\2\0\3\1\1\0\1\1\1\11\2\1\2\0\3\1"+
    "\1\0\1\1\1\11\1\1\2\0\2\1\1\0\1\1"+
    "\2\11\2\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[134];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;
  
  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** the stack of open (nested) input streams to read from */
  private java.util.Stack<ZzFlexStreamInfo> zzStreams
    = new java.util.Stack<ZzFlexStreamInfo>();

  /**
   * inner class used to store info for nested
   * input streams
   */
  private static final class ZzFlexStreamInfo {
    java.io.Reader zzReader;
    int zzEndRead;
    int zzStartRead;
    int zzCurrentPos;
    int zzMarkedPos;
    int yyline;
    int yychar;
    int yycolumn;
    char [] zzBuffer;
    boolean zzAtBOL;
    boolean zzAtEOF;
    boolean zzEOFDone;
    int zzFinalHighSurrogate;

    /** sets all values stored in this class */
    ZzFlexStreamInfo(java.io.Reader zzReader, int zzEndRead, int zzStartRead,
                  int zzCurrentPos, int zzMarkedPos, char [] zzBuffer, 
                  boolean zzAtBOL, boolean zzAtEOF, boolean zzEOFDone,
                  int zzFinalHighSurrogate, int yyline, int yychar, int yycolumn) {
      this.zzReader      = zzReader;
      this.zzEndRead     = zzEndRead;
      this.zzStartRead   = zzStartRead;
      this.zzCurrentPos  = zzCurrentPos;
      this.zzMarkedPos   = zzMarkedPos;
      this.zzBuffer      = zzBuffer;
      this.zzAtBOL       = zzAtBOL;
      this.zzAtEOF       = zzAtEOF;
      this.zzEOFDone     = zzEOFDone;
      this.zzFinalHighSurrogate = zzFinalHighSurrogate;
      this.yyline        = yyline;
      this.yychar        = yychar;
      this.yycolumn      = yycolumn;
    }
  }

  /* user code: */

   public void resetLiteral(String txt) {
      data = true;
      litLine = yyline;
      litColumn = yycolumn;
      cadena = new StringBuilder(txt);
   }

   public Symbol literal(String txt) {
      cadena.append(txt);
      String texto = cadena.toString();
      cadena.setLength(0);
      print("Devuelve LITERAL - " + texto);
      Symbol s = new Symbol(LITERAL, litLine, litColumn, texto);
      return symbolFactory.newSymbol(texto, LITERAL, s);
   }

   public Symbol symbol(int code){
      return symbol(code, yytext());
   }
   
   public Symbol symbol(int code, String txt) {
      data = true;
      print("Devuelve SYMBOL(" + code + ") - (" + (yyline + 1) + "," + (yycolumn + 1) + ") " + txt);
      Symbol s = new Symbol(code, yyline, yycolumn, txt);
      return symbolFactory.newSymbol(txt, code, s);
   }

   public Symbol symbolic(int value) {
      data = true;
      String txt = Integer.toString(value);
      print("Devuelve SYMBOL (" + (yyline + 1) + "," + (yycolumn + 1) + ") " + txt);
      Symbol s = new Symbol(NUMERO, yyline, yycolumn, txt);
      return symbolFactory.newSymbol(txt, NUMERO, s);
   }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public DB2Lexer(java.io.Reader in) {
     initLexer();
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 202) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {      
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Stores the current input stream on a stack, and
   * reads from a new stream. Lexical state, line,
   * char, and column counting remain untouched.
   *
   * The current input stream can be restored with
   * yypopStream (usually in an <<EOF>> action).
   *
   * @param reader the new input stream to read from
   *
   * @see #yypopStream()
   */
  public final void yypushStream(java.io.Reader reader) {
    zzStreams.push(
      new ZzFlexStreamInfo(zzReader, zzEndRead, zzStartRead, zzCurrentPos,
                        zzMarkedPos, zzBuffer, zzAtBOL, zzAtEOF, zzEOFDone,
                        zzFinalHighSurrogate, yyline, yychar, yycolumn)
    );
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzBuffer = new char[ZZ_BUFFERSIZE];
    zzReader = reader;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
  }
    

  /**
   * Closes the current input stream and continues to
   * read from the one on top of the stream stack. 
   *
   * @throws java.util.EmptyStackException
   *         if there is no further stream to read from.
   *
   * @throws java.io.IOException
   *         if there was an error in closing the stream.
   *
   * @see #yypushStream(java.io.Reader)
   */
  public final void yypopStream() throws java.io.IOException {
    zzReader.close();
    ZzFlexStreamInfo s = (ZzFlexStreamInfo) zzStreams.pop();
    zzBuffer      = s.zzBuffer;
    zzReader      = s.zzReader;
    zzEndRead     = s.zzEndRead;
    zzStartRead   = s.zzStartRead;
    zzCurrentPos  = s.zzCurrentPos;
    zzMarkedPos   = s.zzMarkedPos;
    zzAtBOL       = s.zzAtBOL;
    zzAtEOF       = s.zzAtEOF;
    zzEOFDone     = s.zzEOFDone;
    zzFinalHighSurrogate = s.zzFinalHighSurrogate;
    yyline        = s.yyline;
    yychar        = s.yychar;
    yycolumn      = s.yycolumn;
  }


  /**
   * Returns true iff there are still streams left 
   * to read from on the stream stack.
   */
  public final boolean yymoreStreams() {
    return !zzStreams.isEmpty();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   *
   * @see #yypushStream(java.io.Reader)
   * @see #yypopStream()
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      // cached fields:
      int zzCurrentPosL;
      int zzMarkedPosL = zzMarkedPos;
      int zzEndReadL = zzEndRead;
      char [] zzBufferL = zzBuffer;
      char [] zzCMapL = ZZ_CMAP;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {     return symbolFactory.newSymbol("EOF", EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { /* nada */
            }
          case 24: break;
          case 2: 
            { /* do nothing */
            }
          case 25: break;
          case 3: 
            { cadena.append(yytext());
            }
          case 26: break;
          case 4: 
            { module.incLines(data);
                     data = false;
                     popState();
            }
          case 27: break;
          case 5: 
            { 
            }
          case 28: break;
          case 6: 
            { if (litQuote == true) {
                         popState();
                         return literal("");
                     }
                     else {
                        cadena.append(yytext());
                     }
            }
          case 29: break;
          case 7: 
            { if (litQuote == false) {
                         popState();
                         return literal("");
                     }
                     else {
                        cadena.append(yytext());
                     }
            }
          case 30: break;
          case 8: 
            { return symbol(ID);
            }
          case 31: break;
          case 9: 
            { return symbol(IN);
            }
          case 32: break;
          case 10: 
            { /* eat */
            }
          case 33: break;
          case 11: 
            { return symbol(MODE);
            }
          case 34: break;
          case 12: 
            { return symbol(LOCK);
            }
          case 35: break;
          case 13: 
            { return symbol(WORK);
            }
          case 36: break;
          case 14: 
            { return symbol(TABLE);
            }
          case 37: break;
          case 15: 
            { return symbol(SHARE);
            }
          case 38: break;
          case 16: 
            { return symbol(COMMIT);
            }
          case 39: break;
          case 17: 
            { return symbol(CURSOR);
            }
          case 40: break;
          case 18: 
            { return symbol(INCLUDE);
            }
          case 41: break;
          case 19: 
            { return symbol(DECLARE);
            }
          case 42: break;
          case 20: 
            { return symbol(ROLLBACK);
            }
          case 43: break;
          case 21: 
            { return symbol(STATEMENT);
            }
          case 44: break;
          case 22: 
            { return symbol(SAVEPOINT);
            }
          case 45: break;
          case 23: 
            { return symbol(EXCLUSIVE);
            }
          case 46: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
