
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 01 09:52:42 CET 2016
//----------------------------------------------------

package com.jgg.sdp.parser.lang;

/** CUP generated interface containing symbol constants. */
public interface DB2Sym {
  /* terminals */
  public static final int INCLUDE = 8;
  public static final int IN = 9;
  public static final int LOCK = 11;
  public static final int CURSOR = 3;
  public static final int SHARE = 16;
  public static final int LITERAL = 10;
  public static final int SAVEPOINT = 15;
  public static final int ID = 6;
  public static final int ROLLBACK = 14;
  public static final int TABLE = 18;
  public static final int COMMIT = 2;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int NUMERO = 13;
  public static final int ID_FULL = 7;
  public static final int STATEMENT = 17;
  public static final int MODE = 12;
  public static final int DECLARE = 4;
  public static final int EXCLUSIVE = 5;
  public static final int WORK = 19;
}

